language: generic

arch: 
 - arm64

# Define global variables
env:
 - IMGNAME=skycoin/cxplayground:latest

services:
 - docker

# Build docker image
before_install:
 - docker build -t ${IMGNAME} .

# Run test script here
# script:

# Push image to dockerhub
after_success:
 - docker tag ${IMGNAME} ${DOCKER_HUB_PROJECT}:latest
 - docker push ${DOCKER_HUB_PROJECT}:latest
