arch: 
- arm64

# Define global variables
env:
 - IMGNAME=skycoin/cxplayground:latest

services:
 - docker

# Build docker image
before_install:
 - docker build -t ${IMGNAME} .

# Run test script here
# script:

# Push image to dockerhub
after_install:
 - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
 - docker tag ${IMGNAME} ${DOCKER_HUB_PROJECT}:latest
 - docker push ${DOCKER_HUB_PROJECT}:latest
