language: generic

arch: 
 - arm64

# Define global variables
env:
 - IMGNAME=skycoin/cxplayground:latest

services:
 - docker

# Build docker image
before_install:
 - docker build -t ${IMGNAME} .

# Run test script here
# script:

# Push image to dockerhub
after_success:
 - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
 - docker tag ${IMGNAME} ${DOCKER_HUB_PROJECT}/cx-playground:latest
 - docker push ${DOCKER_HUB_PROJECT}/cx-playground:latest
